App\Entity\Material:
    attributes:
        id:
            groups: ['material']
        nombre:
            groups: ['material']
        imagen:
            groups: ['material']
        movimientos:
            groups: ['material']